# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos: 
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        exclude: recipe/meta.yaml
      - id: check-added-large-files
        args: ["--maxkb=50180"]
      - id: detect-private-key
      - id: requirements-txt-fixer

